routes/web.php
<?php

use Bittacora\Bpanel4Users\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth', 'admin-menu'])->name('user.')->group(function(){
    Route::get('/user', [UserController::class, 'index'])->name('index');
    Route::get('/user/create', [UserController::class, 'create'])->name('create');
    Route::get('/user/{user}/show', [UserController::class, 'show'])->name('show');
    Route::get('/user/{user}/edit', [UserController::class, 'edit'])->name('edit');
    Route::post('/user/store', [UserController::class, 'store'])->name('store');
    Route::put('/user/{user}', [UserController::class, 'update'])->name('update');
    Route::delete('/user/{user}', [UserController::class, 'destroy'])->name('destroy');
    Route::post('/user/bulkdelete', [UserController::class, 'bulkDelete'])->name('bulkdelete');
});

resources/views/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Alta de usuario')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::form.add') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('user.store')}}">
            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('user::form.name'), 'labelWidth' => 3, 'required' => true])
            @livewire('form::input-text', ['name' => 'email', 'labelText' => __('user::form.email'), 'labelWidth' => 3, 'required' => true])
            @livewire('form::input-password', ['name' => 'password', 'labelText' => __('user::form.password'), 'labelWidth' => 3, 'required' => true, 'note' => 'Debe contener entre 8 y 16 caracteres'])
            @livewire('form::input-password', ['name' => 'repeatPassword', 'labelText' => __('user::form.repeat_password'), 'labelWidth' => 3, 'required' => true])
            @livewire('form::input-checkbox', ['name' => 'active', 'labelText' => __('user::form.active'), 'bpanelForm' => true, 'checked' => true])

            @if(!empty($roles))
                @livewire('form::dual-list-box', ['name' => 'roles[]', 'idField' => 'roleSelect', 'labelText' => __('user::form.assign_roles_to_user'), 'allValues' => $roles, 'height' => '232px'])
            @endif


            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>

@endsection

resources/views/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Edición de usuario: ' . $user->name)

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::form.edit') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('user.update', $user)}}">
            @method('PUT')
            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('user::form.name'), 'labelWidth' => 3, 'required' => true, 'value' => $user->name])
            @livewire('form::input-text', ['name' => 'email', 'labelText' => __('user::form.email'), 'labelWidth' => 3, 'required' => true, 'value' => $user->email])
            @livewire('form::input-password', ['name' => 'password', 'labelText' => __('user::form.password'), 'labelWidth' => 3])
            @livewire('form::input-password', ['name' => 'repeatPassword', 'labelText' => __('user::form.repeat_password'), 'labelWidth' => 3])
            @livewire('form::input-checkbox', ['name' => 'active', 'labelText' => __('user::form.active'), 'bpanelForm' => true, 'checked' => $user->active])
            @livewire('form::input-checkbox', ['name' => 'changePassword', 'labelText' => __('user::form.change_password'), 'bpanelForm' => true, 'checked' => false])

            @if(!empty($roles))
                @livewire('form::dual-list-box', ['name' => 'roles[]', 'idField' => 'roleSelect', 'labelText' => __('user::form.assign_roles_to_user'),
                'allValues' => $roles, 'height' => '232px', 'selectedValues' => $userRoles])
            @endif

            @livewire('utils::created-updated-info', ['model' => $user])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>

@endsection

resources/views/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Usuarios')

@section('content')

    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('user::user-datatable', [], key('user-datatable'))
        </div>
    </div>


@endsection

resources/views/livewire/datatable-checkbox.blade.php
<div class="form-check form-check-inline text-center mr-0">
    <input class="form-check-input ace-switch mr-0"
           type="checkbox"
           @if($multiple) name="{{$name}}[]" @else name="{{$name}}" @endif
           id="{{$idField}}"
           wire:click="toggle({{$idField}})"
           @if($value==1) checked @endif
    >
    @if(!is_null($labelText))
        <label class="form-check-label" for="{{$idField}}">{{ $labelText }}</label>
    @endif
</div>

resources/views/livewire/datatable-columns/actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'user', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el usuario?'], key('user-buttons-'.$row->id))

resources/views/livewire/datatable-columns/active.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))

resources/views/livewire/user-datatable.blade.php
<td>
    <div class="text-center">
        {{$row->name}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->email}}
    </div>
</td>
<td>
    <div class="text-center">
        {{\Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $row->created_at)->format('d/m/Y H:i')}}
    </div>
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td>
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'user', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el usuario?'], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/partials/actions.blade.php
<div class="action-buttons">
    <a class="text-blue mx-2" href="{{route($scope.'.show',$id)}}">
        <i class="fa fa-search"></i>
    </a>
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        @method('DELETE')
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/partials/active.blade.php
<div class="text-center">
    @livewire('datatable-checkbox',[
    'idField' => $idField,
    'name' => $name,
    'value' => $value,
 ])
</div>

resources/views/show.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Datos de usuario: ' . $user->name)

@section('content')

    <div class="card-header bgc-primary-d1 text-white border-0">
        <h4 class="text-120 mb-0">
            <span class="text-90">{{ __('user::datatable.user_info') }}</span>
        </h4>
    </div>
    <table class="table">
        <tbody>
            <tr>
                <td class="col-sm-2"><strong>{{ __('user::datatable.name') }}</strong></td>
                <td>
                    {{ $user->name }}
                </td>
            </tr>
            <tr>
                <td class="col-sm-2"><strong>{{ __('user::datatable.email') }}</strong></td>
                <td>
                    {{ $user->email }}
                </td>
            </tr>
            <tr>
                <td class="col-sm-2"><strong>{{ __('user::datatable.active') }}</strong></td>
                <td>
                    @if($user->active) {{ __('user::datatable.yes') }} @else {{ __('user::datatable.no') }} @endif
                </td>
            </tr>
            <tr>
                <td class="col-sm-2"><strong>{{ __('user::datatable.created_date') }}</strong></td>
                <td>
                    {{ $user->created_at->format('d/m/Y H:i:s') }} @if(!is_null($user->created_by)) - {{ \Bittacora\Bpanel4Users\UserFacade::getNameById($user->created_by) }} @endif
                </td>
            </tr>
            <tr>
                <td class="col-sm-2"><strong>{{ __('user::datatable.updated_date') }}</strong></td>
                <td>
                    {{ $user->updated_at->format('d/m/Y H:i:s') }} @if(!is_null($user->updated_by)) - {{ \Bittacora\Bpanel4Users\UserFacade::getNameById($user->updated_by) }} @endif
                </td>
            </tr>
            <tr>
                <td class="col-sm-2"><strong>Roles</strong></td>
                <td>
                    @foreach($user->roles as $role)
                        {{$role->name}} @if(!$loop->last) / @endif
                    @endforeach
                </td>
            </tr>
        </tbody>
    </table>

@endsection